[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
dirs = "5.0"
tokio = { version = "1", features = ["fs", "macros", "rt-multi-thread"] }
hex.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["fs"] }

[dev-dependencies]
reqwest.workspace = true
