[alias]
arrow = "run -p arrow@0.1.0 --"
autopilot = "run -p autopilot-desktop-runner --"
manatap = "run -p manatap --"
storybook = "run -p wgpui --example storybook --features desktop"
pylon = "run -p pylon --release --"
pylon-desktop = "run -p pylon-desktop --release --"
onyx = "run -p onyx --"
ws = "run -p ws-test -- --host 127.0.0.1 --port 8081 --app-key local-key"
