[alias]
arrow = "run -p arrow@0.1.0 --"
autopilot = "run -p autopilot --"
manatap = "run -p manatap --"
storybook = "run -p wgpui --example storybook --features desktop"
pylon = "run -p pylon --release --"
pylon-desktop = "run -p pylon-desktop --release --"
onyx = "run -p onyx --"
