[alias]
openagents = "run --bin openagents --"
autopilot = "run --bin autopilot --"
desktop = "run -p desktop"
storybook = "run -p wgpui --example storybook --features desktop"
pylon = "run -p pylon-desktop --release --"
onyx = "run -p onyx --"
