apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openagents-staging

resources:
  - ../../base

images:
  - name: runtime
    newName: us-central1-docker.pkg.dev/PROJECT_ID/runtime/runtime
    newTag: staging-latest

patches:
  - path: patch-statefulset.yaml
  - path: patch-hpa.yaml
  - path: patch-pdb.yaml
